### ISSUE TITLE
Faraday gem version

### ISSUE THREAD

**Issue by OleksandrPoltavets** [taylorstib/eia_fuel#2]
Hi @taylorstib, could you please bump Faraday gem version dependency to 1.0?
I made a form from your repository, it works for my project: https://github.com/OleksandrPoltavets/eia_fuel/blob/master/eia_fuel.gemspec#L22

**Comment by taylorstib** [comment]
Hey @OleksandrPoltavets, I'll make the update!

**Comment by OleksandrPoltavets** [comment]
Awesome, thanks @taylorstib!

**Comment by taylorstib** [comment]
New version has been published to ruby gems. v0.2.0

**Comment by taylorstib** [comment]
@OleksandrPoltavets I also updated the base URL to `https` in this version so please let me know if that causes any issues
